---
- name: create ticket with notes
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:
  - name: include vars
    include_vars: incident_vars.yml

  - name: show version
    ios_command:
      commands:
        - show version
    register: version

  - name: parse show version
    command_parser:
      file: "parsers/show_version.yaml"
      content: "{{ version.stdout.0 }}"

  - name: build comments
    set_fact:
      comments: "{{ lookup('template', 'comments.j2') }}"

  - name: Create an incident
    snow_record:
      username: "{{ username }}"
      password: "{{ password }}'
      instance: "{{ instance }}"
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: "{{ severity}}"
        priority: "{{ priority}}"
        comments: "{{ comments }}"
    register: new_incident
